#!/bin/bash

#PBS -N xx18
#PBS -l select=4
#PBS -l walltime=12:00:00
#PBS -A z01-csetds

export PBS_O_WORKDIR=$(readlink -f $PBS_O_WORKDIR)
cd $PBS_O_WORKDIR

# When the default modules are up to date, then only this line is
# needed.
#module load cray-petsc-64
module unload modules
module load modules/3.2.10.5
source $MODULESHOME/init/bash
module load cdt/16.09 &> /dev/null
module unload cray-petsc-64
module unload cray-tpsl-64
module load cray-tpsl-64/16.07.1
module load cray-petsc-64/3.7.2.1

## CrayPat
#module unload perftools
#module unload perftools-base
#module load perftools-base/6.4.2
#module load perftools/6.4.2

module use $HOME/modulefiles
module load parafem


s=4 # 4 nodes
# Maximum number of partitions is 100 (1-D partitioning) so don't go up to 96.
#for N in 24 12 6 3 2 1; do
for N in 12 6 3 2 1; do
    n=$((s*N))
    d=$((24/N))

    mkdir -p parafem_$n
    aprun -n $n -N $N -d $d xx18 xx18_large &> log
    cp -p log *.res parafem_$n
    
    mkdir -p petsc_$n
    aprun -n $n -N $N -d $d xx18 xx18_large petsc &> log
    cp -p log *.res petsc_$n
done
