PROGRAM iotest
! Program to prototype, implement and test I/O subroutines
! Loads array need sorting out

 IMPLICIT NONE

 USE precision
 
 INTEGER   :: i, j, ndim, nod, nn, nels, nodof, nfe
 REAL(iwp) :: zero = 0.0_iwp
 
 INTEGER, ALLOCATABLE   :: g_num(:,:), nf(:,:), etype(:)
 REAL(iwp), ALLOCATABLE :: g_coord(:,:), loads(:,:), disp(:,:)
 
 LOGICAL   :: hardcoded=.true.

!------------------------------------------------------------------------------
!------------------------------------------------------------------------------
! 1. Hard coded data for one element
!------------------------------------------------------------------------------
!------------------------------------------------------------------------------

  PRINT *, "Program currently writes ascii data into file named binary"
  
  ndim  = 3
  nod   = 8
  nn    = 8
  nels  = 1
  nodof = ndim + 1
  
  ALLOCATE (g_coord(ndim,nn))
  ALLOCATE (g_num(nod,nels))
  ALLOCATE (nf(nodof,nn))
  ALLOCATE (etype(nels))
  ALLOCATE (disp(ndim,nn))
  
  g_coord = zero
  g_num   = 0
  nf      = 0
  etype   = 0
  disp    = zero
  
  IF(hardcoded == .true.) THEN
  
    g_coord(:,1) = (/0.0,0.0,0.0/)
    g_coord(:,2) = (/0.0,0.0,1.0/)
    g_coord(:,3) = (/1.0,0.0,1.0/)
    g_coord(:,4) = (/1.0,0.0,0.0/)
    g_coord(:,5) = (/0.0,1.0,0.0/)
    g_coord(:,6) = (/0.0,1.0,1.0/)
    g_coord(:,7) = (/1.0,1.0,1.0/)
    g_coord(:,8) = (/1.0,1.0,0.0/)
  
    g_num(:,1) = (/1,2,3,4,5,6,7,8/)
  
    nf(:,1) = (/1,0,0,0/)
    nf(:,2) = (/2,1,1,1/)
    nf(:,3) = (/3,1,1,1/)
    nf(:,4) = (/4,1,1,0/)
    nf(:,5) = (/5,1,1,0/)
    nf(:,6) = (/6,1,1,1/)
    nf(:,7) = (/7,1,1,1/)
    nf(:,8) = (/8,1,1,0/)
  
    etype(1) = (/1/)
  
    disp(:,1) = (/0.0,0.0,0.0/)
    disp(:,2) = (/0.0,0.0,-0.1/)
    disp(:,3) = (/0.0,0.0,-0.2/)
    disp(:,4) = (/0.0,0.0,0.0/)
    disp(:,5) = (/0.0,0.0,0.0/)
    disp(:,6) = (/0.0,0.0,-0.1/)
    disp(:,7) = (/0.0,0.0,-0.2/)
    disp(:,8) = (/0.0,0.0,0.0/)
    
  END IF
  
!------------------------------------------------------------------------------
!------------------------------------------------------------------------------
! 2. ASCII Ensight Gold Format
!------------------------------------------------------------------------------
!------------------------------------------------------------------------------

!------------------------------------------------------------------------------
! 2.1 Write ASCII Ensight Gold Case File
!------------------------------------------------------------------------------

  OPEN(20,FILE='ASCII.ensi.case')
  
  WRITE(20,'(A/A)')    "#", "# Post-processing file generated by program      &
                             &iotest.f90 "
  WRITE(20,'(A/A/A)')  "#","# Ensight Gold Format","#"
  WRITE(20,'(2A/A)')   "# Problem name: ",argv(1:nlen),"#"
  WRITE(20,'(A/A/A)')  "FORMAT","type:  ensight gold","GEOMETRY"
  WRITE(20,'(2A/A)')   "model: 1  ",argv(1:nlen)//'.ensi.geo',"VARIABLE"
  WRITE(20,'(2A)')     "scalar per element:  material      ",                 &
                        argv(1:nlen)//'.ensi.MATID' 
  WRITE(20,'(2A)')     "scalar per node:     restraint     ",                 &
                        argv(1:nlen)//'.ensi.NDBND'
  WRITE(20,'(2A)')     "vector per node:     displacement  ",                 &
                        argv(1:nlen)//'.ensi.DISPL-******'

  CLOSE(20)

!------------------------------------------------------------------------------
! 2.2 Write ASCII geometry file
!------------------------------------------------------------------------------
  
  OPEN(21,FILE='ASCII.ensi.geo')
  
  WRITE(21,'(/2A)')   "Problem name: ", "ASCII"
  WRITE(21,'(A/A/A)') "Geometry files","node id given","element id given"
  WRITE(21,'(A/A)')   "part","      1"
  WRITE(21,'(A)')     "Volume Mesh"
  WRITE(21,'(A)')     "coordinates"
  
  WRITE(21,'(I10)') nn
  DO j=1,ndim
    DO i=1,nn  
      WRITE(21,'(E12.5)') g_coord(j,i)
    END DO
  END DO
  
  DO i = 1,nels
    WRITE(21,'(8I10)') g_num(1,i),g_num(4,i),g_num(8,i),g_num(5,i),           &
                       g_num(2,i),g_num(3,i),g_num(7,i),g_num(6,i)
  END DO

  CLOSE(21)
    
!------------------------------------------------------------------------------
! 2.3 Write ASCII Boundary Conditions
!------------------------------------------------------------------------------

  OPEN(22,FILE='ASCII.ensi.NDBND')
  WRITE(22,'(A)')     "Alya Ensight Gold --- Scalar per-node variable file"
  WRITE(22,'(A/A/A)') "part", "      1","coordinates"

  DO i=1,UBOUND(g_coord,2) 
    nfe=0
    IF(nf(1,i)==0) nfe=nfe+1
    IF(nf(2,i)==0) nfe=nfe+2
    IF(nf(3,i)==0) nfe=nfe+4
    WRITE(22,'(I2)') nfe
  END DO

  CLOSE(22)

!------------------------------------------------------------------------------
! 2.4 Write ASCII Loaded Nodes
!------------------------------------------------------------------------------

! OPEN(23,FILE='ASCII.ensi.NDLDS')
! WRITE(23,'(A)')     "Alya Ensight Gold --- Vector per-node variable file"
! WRITE(23,'(A/A/A)') "part", "      1","coordinates"

! DO j=1,UBOUND(nf,1)
!   DO i=1, UBOUND(nf,2)
!     WRITE(23,'(E12.5)') loads(nf(j,i))
!   END DO
! END DO

! CLOSE(23)

!------------------------------------------------------------------------------
! 2.5 Write ASCII file containing material IDs
!------------------------------------------------------------------------------
  
  OPEN(24,FILE='ASCII.ensi.MATID')

  WRITE(24,'(A)') "Alya Ensight Gold --- Scalar per-element variable file"
  WRITE(24,'(A/A)') "part", "      1"
  WRITE(24,'(A)') "hexa8"
  DO i=1,nels; WRITE(24,'(I10)') etype(i); END DO  

  CLOSE(24)
  
!------------------------------------------------------------------------------
! 2.6 Write ASCII Displacements
!------------------------------------------------------------------------------

  OPEN(25,file='ASCII.ensi.DISPL-000001',status='replace',action='write')
       
  WRITE(25,'(A)') "Alya Ensight Gold --- Vector per-node variable file"
  WRITE(25,'(A/A/A)') "part", "     1","coordinates"  

  DO i=1,nn
    WRITE(25,'(e12.4)') disp(i)
  END DO

  CLOSE(25)

!------------------------------------------------------------------------------
!------------------------------------------------------------------------------
! 3. BINARY Ensight Gold Format
!------------------------------------------------------------------------------
!------------------------------------------------------------------------------

!------------------------------------------------------------------------------
! 3.1 Write BINARY Ensight Gold Case File
!------------------------------------------------------------------------------

  OPEN(26,FILE='BINARY.ensi.case')
  
  WRITE(26,'(A/A)')    "#", "# Post-processing file generated by program      &
                             &iotest.f90 "
  WRITE(26,'(A/A/A)')  "#","# Ensight Gold Format","#"
  WRITE(26,'(2A/A)')   "# Problem name: ",argv(1:nlen),"#"
  WRITE(26,'(A/A/A)')  "FORMAT","type:  ensight gold","GEOMETRY"
  WRITE(26,'(2A/A)')   "model: 1  ",argv(1:nlen)//'.ensi.geo',"VARIABLE"
  WRITE(26,'(2A)')     "scalar per element:  material      ",                 &
                        argv(1:nlen)//'.ensi.MATID' 
  WRITE(26,'(2A)')     "scalar per node:     restraint     ",                 &
                        argv(1:nlen)//'.ensi.NDBND'
  WRITE(26,'(2A)')     "vector per node:     displacement  ",                 &
                        argv(1:nlen)//'.ensi.DISPL-******'

  CLOSE(26)

!------------------------------------------------------------------------------
! 3.2 Write BINARY Geometry File
!------------------------------------------------------------------------------

  OPEN(27,FILE='BINARY.ensi.geo')
  
  WRITE(27,'(/2A)')   "Problem name: ", "ASCII"
  WRITE(27,'(A/A/A)') "Geometry files","node id given","element id given"
  WRITE(27,'(A/A)')   "part","      1"
  WRITE(27,'(A)')     "Volume Mesh"
  WRITE(27,'(A)')     "coordinates"
  
  WRITE(27,'(I10)') nn
  DO j=1,ndim
    DO i=1,nn  
      WRITE(27,'(E12.5)') g_coord(j,i)
    END DO
  END DO
  
  DO i = 1,nels
    WRITE(27,'(8I10)') g_num(1,i),g_num(4,i),g_num(8,i),g_num(5,i),           &
                       g_num(2,i),g_num(3,i),g_num(7,i),g_num(6,i)
  END DO

  CLOSE(27)
  
!------------------------------------------------------------------------------
! 3.3 Write BINARY Boundary Conditions
!------------------------------------------------------------------------------

  OPEN(28,FILE='BINARY.ensi.NDBND')
  WRITE(28,'(A)')     "Alya Ensight Gold --- Scalar per-node variable file"
  WRITE(28,'(A/A/A)') "part", "      1","coordinates"

  DO i=1,UBOUND(g_coord,2) 
    nfe=0
    IF(nf(1,i)==0) nfe=nfe+1
    IF(nf(2,i)==0) nfe=nfe+2
    IF(nf(3,i)==0) nfe=nfe+4
    WRITE(22,'(I2)') nfe
  END DO

  CLOSE(28)
  
!------------------------------------------------------------------------------
! 3.4 Write BINARY Loaded Nodes
!------------------------------------------------------------------------------

! OPEN(29,FILE='BINARY.ensi.NDLDS')
! WRITE(29,'(A)')     "Alya Ensight Gold --- Vector per-node variable file"
! WRITE(29,'(A/A/A)') "part", "      1","coordinates"

! DO j=1,UBOUND(nf,1)
!   DO i=1, UBOUND(nf,2)
!     WRITE(23,'(E12.5)') loads(nf(j,i))
!   END DO
! END DO

! CLOSE(29)

!------------------------------------------------------------------------------
! 2.5 Write BINARY file containing material IDs
!------------------------------------------------------------------------------
  
  OPEN(30,FILE='BINARY.ensi.MATID')

  WRITE(30,'(A)') "Alya Ensight Gold --- Scalar per-element variable file"
  WRITE(30,'(A/A)') "part", "      1"
  WRITE(30,'(A)') "hexa8"
  DO i=1,nels; WRITE(24,'(I10)') etype(i); END DO  

  CLOSE(30)

!------------------------------------------------------------------------------
! 2.6 Write ASCII Displacements
!------------------------------------------------------------------------------

  OPEN(31,file='BINARY.ensi.DISPL-000001',status='replace',action='write')
       
  WRITE(31,'(A)') "Alya Ensight Gold --- Vector per-node variable file"
  WRITE(31,'(A/A/A)') "part", "     1","coordinates"  

  DO i=1,nn
    WRITE(31,'(e12.4)') disp(i)
  END DO

  CLOSE(31)
  
END PROGRAM iotest