#!/bin/bash

#PBS -N xx15
#PBS -l select=1
#PBS -l walltime=00:20:00
#PBS -A z01-cse
#PBS -q short

export PBS_O_WORKDIR=$(readlink -f $PBS_O_WORKDIR)
cd $PBS_O_WORKDIR

module use $HOME/modulefiles
module load parafem

mkdir -p parafem
aprun -n 24 xx15_vm_nonlinear_hardening input &> parafem/log
cp -p *.res parafem

mkdir -p petsc
aprun -n 24 xx15_vm_nonlinear_hardening input petsc &> petsc/log
cp -p *.res petsc
