#!/bin/bash

BINLOC=`echo $0 | sed -e 's_inp2pf$__g' -`

# --------------------------------------------------------------------------------
# Process command line arguments
# --------------------------------------------------------------------------------

while [ $# -gt 0 ]; do
    ARG=`echo $1 | tr "[:upper:]" "[:lower:]"`
    case $ARG in
	-usage) showusage; exit;;
	-help) showusage; exit;;

	-renumber) INP2PF_ARGS="-v renumber=1";;

	-*) unknown-arg; showusage; exit;;
	*) INP_FILENAME=$1
    esac
    shift
done

echo "Converting $1 to ParaFEM Format"
awk -f $BINLOC/inp2pf.awk $INP2PF_ARGS $INP_FILENAME

showusage() {
    echo "To capture a log file, please run the script as:"
    echo "  ./inp2pf <ARGS> 2>&1 | tee log"
    echo
    echo "Modifying conversion options:"
    echo "  -renumber will renumber both node IDs and element IDs as ParaFEM requires contiguous IDs starting at 1"
    echo
}
