#!/bin/sh

echo "Starting ParaFEM Viewer ..."

export XP_LICENSE_SERVER=thomas.rcs.manchester.ac.uk:33333
export XP_FEATURE=VIZ_EXPRESS
export MACHINE=linux_64
export LD_LIBRARY_PATH=$PWD/${0%/*}/lib/$MACHINE:$LD_LIBRARY_PATH
cd ${0%/*}
bin/$MACHINE/express -novcp $*
